// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GenesisCloud
{
    /// <summary>
    /// SSH key resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using GenesisCloud = Pulumi.GenesisCloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new GenesisCloud.SSHKey("example", new()
    ///     {
    ///         PublicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBOpdKM8wSI07+PO4xLDL7zW/kNWGbdFXeHyBU1TRlBn alice@example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import genesiscloud:index/sSHKey:SSHKey example 18efeec8-94f0-4776-8ff2-5e9b49c74608
    /// ```
    /// </summary>
    [GenesisCloudResourceType("genesiscloud:index/sSHKey:SSHKey")]
    public partial class SSHKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when this SSH key was created in RFC 3339.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The fingerprint of the SSH key.
        /// </summary>
        [Output("fingerprint")]
        public Output<string> Fingerprint { get; private set; } = null!;

        /// <summary>
        /// The human-readable name for the SSH key.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.SSHKeyTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a SSHKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SSHKey(string name, SSHKeyArgs args, CustomResourceOptions? options = null)
            : base("genesiscloud:index/sSHKey:SSHKey", name, args ?? new SSHKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SSHKey(string name, Input<string> id, SSHKeyState? state = null, CustomResourceOptions? options = null)
            : base("genesiscloud:index/sSHKey:SSHKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/genesiscloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SSHKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SSHKey Get(string name, Input<string> id, SSHKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new SSHKey(name, id, state, options);
        }
    }

    public sealed class SSHKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The human-readable name for the SSH key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("publicKey", required: true)]
        public Input<string> PublicKey { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.SSHKeyTimeoutsArgs>? Timeouts { get; set; }

        public SSHKeyArgs()
        {
        }
        public static new SSHKeyArgs Empty => new SSHKeyArgs();
    }

    public sealed class SSHKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The timestamp when this SSH key was created in RFC 3339.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The fingerprint of the SSH key.
        /// </summary>
        [Input("fingerprint")]
        public Input<string>? Fingerprint { get; set; }

        /// <summary>
        /// The human-readable name for the SSH key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        [Input("timeouts")]
        public Input<Inputs.SSHKeyTimeoutsGetArgs>? Timeouts { get; set; }

        public SSHKeyState()
        {
        }
        public static new SSHKeyState Empty => new SSHKeyState();
    }
}
