// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GenesisCloud.PulumiPackage.Genesiscloud.Outputs
{

    [OutputType]
    public sealed class ImagesFilterResult
    {
        /// <summary>
        /// Filter by the region identifier.
        ///   - The value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// Filter by the kind of image.
        ///   - The value must be one of: ["base-os" "cloud-image" "preconfigured" "snapshot"].
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private ImagesFilterResult(
            string? region,

            string type)
        {
            Region = region;
            Type = type;
        }
    }
}
