// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/genesiscloud/pulumi-genesiscloud/sdk/go/genesiscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Genesis Cloud API endpoint. May also be provided via `GENESISCLOUD_ENDPOINT` environment variable. If neither is
// provided, defaults to `https://api.genesiscloud.com/compute/v1`.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "genesiscloud:endpoint")
}

// The polling interval. - The string must be a positive [time duration](https://pkg.go.dev/time#ParseDuration), for
// example "10s".
func GetPollingInterval(ctx *pulumi.Context) string {
	return config.Get(ctx, "genesiscloud:pollingInterval")
}

// Genesis Cloud API token. May also be provided via `GENESISCLOUD_TOKEN` environment variable.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "genesiscloud:token")
}
