// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GenesisCloud.PulumiPackage.Genesiscloud
{
    /// <summary>
    /// Instance resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Genesiscloud = GenesisCloud.PulumiPackage.Genesiscloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Genesiscloud.Instance("example", new()
    ///     {
    ///         Image = "my-image-id",
    ///         Region = "ARC-IS-HAF-1",
    ///         SshKeyIds = new[]
    ///         {
    ///             "my-ssh-key-id",
    ///         },
    ///         Type = "vcpu-2_memory-4g",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import genesiscloud:index/instance:Instance example 18efeec8-94f0-4776-8ff2-5e9b49c74608
    /// ```
    /// </summary>
    [GenesiscloudResourceType("genesiscloud:index/instance:Instance")]
    public partial class Instance : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when this image was created in RFC 3339.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The disk size of the instance in GB.
        /// </summary>
        [Output("diskSize")]
        public Output<int> DiskSize { get; private set; } = null!;

        /// <summary>
        /// The floating IP attached to the instance.
        /// </summary>
        [Output("floatingIpId")]
        public Output<string?> FloatingIpId { get; private set; } = null!;

        /// <summary>
        /// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
        /// attribute is configured and changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// The source image id, image slug or snapshot id of the instance. The image version can also specified together with the
        /// image slug in this format `&lt;image-slug&gt;:&lt;version&gt;`. Learn more about images
        /// [here](https://developers.genesiscloud.com/images). - If the value of this attribute changes, Terraform will destroy and
        /// recreate the resource.
        /// </summary>
        [Output("image")]
        public Output<string> Image { get; private set; } = null!;

        /// <summary>
        /// The resulting image ID of the instance.
        /// </summary>
        [Output("imageId")]
        public Output<string> ImageId { get; private set; } = null!;

        /// <summary>
        /// Option to provide metadata. Currently supported is `startup_script`.
        /// </summary>
        [Output("metadata")]
        public Output<Outputs.InstanceMetadata?> Metadata { get; private set; } = null!;

        /// <summary>
        /// The human-readable name for the instance.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
        /// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
        /// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
        /// length must be at least 16.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// The placement option identifier in which instances are physically located relative to each other within a zone. For
        /// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Output("placementOption")]
        public Output<string> PlacementOption { get; private set; } = null!;

        /// <summary>
        /// The private IPv4 IP-Address (IPv4 address).
        /// </summary>
        [Output("privateIp")]
        public Output<string> PrivateIp { get; private set; } = null!;

        /// <summary>
        /// The public IPv4 IP-Address (IPv4 address).
        /// </summary>
        [Output("publicIp")]
        public Output<string> PublicIp { get; private set; } = null!;

        /// <summary>
        /// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
        /// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// The id of the reservation the instance is associated with.
        /// </summary>
        [Output("reservationId")]
        public Output<string?> ReservationId { get; private set; } = null!;

        /// <summary>
        /// The security groups of the instance. If not provided will be set to the default security group.
        /// </summary>
        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        /// <summary>
        /// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
        /// resource.
        /// </summary>
        [Output("sshKeyIds")]
        public Output<ImmutableArray<string>> SshKeyIds { get; private set; } = null!;

        /// <summary>
        /// The instance status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.InstanceTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// The instance type identifier. Learn more about instance types
        /// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
        /// Terraform will destroy and recreate the resource.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// The timestamp when this image was last updated in RFC 3339.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// The volumes of the instance.
        /// </summary>
        [Output("volumeIds")]
        public Output<ImmutableArray<string>> VolumeIds { get; private set; } = null!;


        /// <summary>
        /// Create a Instance resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Instance(string name, InstanceArgs args, CustomResourceOptions? options = null)
            : base("genesiscloud:index/instance:Instance", name, args ?? new InstanceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Instance(string name, Input<string> id, InstanceState? state = null, CustomResourceOptions? options = null)
            : base("genesiscloud:index/instance:Instance", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/genesiscloud",
                AdditionalSecretOutputs =
                {
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Instance resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Instance Get(string name, Input<string> id, InstanceState? state = null, CustomResourceOptions? options = null)
        {
            return new Instance(name, id, state, options);
        }
    }

    public sealed class InstanceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The disk size of the instance in GB.
        /// </summary>
        [Input("diskSize")]
        public Input<int>? DiskSize { get; set; }

        /// <summary>
        /// The floating IP attached to the instance.
        /// </summary>
        [Input("floatingIpId")]
        public Input<string>? FloatingIpId { get; set; }

        /// <summary>
        /// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
        /// attribute is configured and changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The source image id, image slug or snapshot id of the instance. The image version can also specified together with the
        /// image slug in this format `&lt;image-slug&gt;:&lt;version&gt;`. Learn more about images
        /// [here](https://developers.genesiscloud.com/images). - If the value of this attribute changes, Terraform will destroy and
        /// recreate the resource.
        /// </summary>
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        /// <summary>
        /// Option to provide metadata. Currently supported is `startup_script`.
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.InstanceMetadataArgs>? Metadata { get; set; }

        /// <summary>
        /// The human-readable name for the instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
        /// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
        /// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
        /// length must be at least 16.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The placement option identifier in which instances are physically located relative to each other within a zone. For
        /// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("placementOption")]
        public Input<string>? PlacementOption { get; set; }

        /// <summary>
        /// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
        /// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// The id of the reservation the instance is associated with.
        /// </summary>
        [Input("reservationId")]
        public Input<string>? ReservationId { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The security groups of the instance. If not provided will be set to the default security group.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("sshKeyIds")]
        private InputList<string>? _sshKeyIds;

        /// <summary>
        /// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
        /// resource.
        /// </summary>
        public InputList<string> SshKeyIds
        {
            get => _sshKeyIds ?? (_sshKeyIds = new InputList<string>());
            set => _sshKeyIds = value;
        }

        [Input("timeouts")]
        public Input<Inputs.InstanceTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// The instance type identifier. Learn more about instance types
        /// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
        /// Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("volumeIds")]
        private InputList<string>? _volumeIds;

        /// <summary>
        /// The volumes of the instance.
        /// </summary>
        public InputList<string> VolumeIds
        {
            get => _volumeIds ?? (_volumeIds = new InputList<string>());
            set => _volumeIds = value;
        }

        public InstanceArgs()
        {
        }
        public static new InstanceArgs Empty => new InstanceArgs();
    }

    public sealed class InstanceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The timestamp when this image was created in RFC 3339.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The disk size of the instance in GB.
        /// </summary>
        [Input("diskSize")]
        public Input<int>? DiskSize { get; set; }

        /// <summary>
        /// The floating IP attached to the instance.
        /// </summary>
        [Input("floatingIpId")]
        public Input<string>? FloatingIpId { get; set; }

        /// <summary>
        /// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
        /// attribute is configured and changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// The source image id, image slug or snapshot id of the instance. The image version can also specified together with the
        /// image slug in this format `&lt;image-slug&gt;:&lt;version&gt;`. Learn more about images
        /// [here](https://developers.genesiscloud.com/images). - If the value of this attribute changes, Terraform will destroy and
        /// recreate the resource.
        /// </summary>
        [Input("image")]
        public Input<string>? Image { get; set; }

        /// <summary>
        /// The resulting image ID of the instance.
        /// </summary>
        [Input("imageId")]
        public Input<string>? ImageId { get; set; }

        /// <summary>
        /// Option to provide metadata. Currently supported is `startup_script`.
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.InstanceMetadataGetArgs>? Metadata { get; set; }

        /// <summary>
        /// The human-readable name for the instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
        /// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
        /// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
        /// length must be at least 16.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The placement option identifier in which instances are physically located relative to each other within a zone. For
        /// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("placementOption")]
        public Input<string>? PlacementOption { get; set; }

        /// <summary>
        /// The private IPv4 IP-Address (IPv4 address).
        /// </summary>
        [Input("privateIp")]
        public Input<string>? PrivateIp { get; set; }

        /// <summary>
        /// The public IPv4 IP-Address (IPv4 address).
        /// </summary>
        [Input("publicIp")]
        public Input<string>? PublicIp { get; set; }

        /// <summary>
        /// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
        /// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The id of the reservation the instance is associated with.
        /// </summary>
        [Input("reservationId")]
        public Input<string>? ReservationId { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The security groups of the instance. If not provided will be set to the default security group.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("sshKeyIds")]
        private InputList<string>? _sshKeyIds;

        /// <summary>
        /// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
        /// resource.
        /// </summary>
        public InputList<string> SshKeyIds
        {
            get => _sshKeyIds ?? (_sshKeyIds = new InputList<string>());
            set => _sshKeyIds = value;
        }

        /// <summary>
        /// The instance status.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.InstanceTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// The instance type identifier. Learn more about instance types
        /// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
        /// Terraform will destroy and recreate the resource.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The timestamp when this image was last updated in RFC 3339.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        [Input("volumeIds")]
        private InputList<string>? _volumeIds;

        /// <summary>
        /// The volumes of the instance.
        /// </summary>
        public InputList<string> VolumeIds
        {
            get => _volumeIds ?? (_volumeIds = new InputList<string>());
            set => _volumeIds = value;
        }

        public InstanceState()
        {
        }
        public static new InstanceState Empty => new InstanceState();
    }
}
