// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GenesisCloud.PulumiPackage.Genesiscloud
{
    /// <summary>
    /// The provider type for the genesiscloud package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [GenesiscloudResourceType("pulumi:providers:genesiscloud")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Genesis Cloud API endpoint. May also be provided via `GENESISCLOUD_ENDPOINT` environment variable. If neither is
        /// provided, defaults to `https://api.genesiscloud.com/compute/v1`.
        /// </summary>
        [Output("endpoint")]
        public Output<string?> Endpoint { get; private set; } = null!;

        /// <summary>
        /// The polling interval. - The string must be a positive [time duration](https://pkg.go.dev/time#ParseDuration), for
        /// example "10s".
        /// </summary>
        [Output("pollingInterval")]
        public Output<string?> PollingInterval { get; private set; } = null!;

        /// <summary>
        /// Genesis Cloud API token. May also be provided via `GENESISCLOUD_TOKEN` environment variable.
        /// </summary>
        [Output("token")]
        public Output<string?> Token { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("genesiscloud", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/genesiscloud",
                AdditionalSecretOutputs =
                {
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Genesis Cloud API endpoint. May also be provided via `GENESISCLOUD_ENDPOINT` environment variable. If neither is
        /// provided, defaults to `https://api.genesiscloud.com/compute/v1`.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        /// <summary>
        /// The polling interval. - The string must be a positive [time duration](https://pkg.go.dev/time#ParseDuration), for
        /// example "10s".
        /// </summary>
        [Input("pollingInterval")]
        public Input<string>? PollingInterval { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Genesis Cloud API token. May also be provided via `GENESISCLOUD_TOKEN` environment variable.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
            Endpoint = Utilities.GetEnv("GENESISCLOUD_ENDPOINT");
            Token = Utilities.GetEnv("GENESISCLOUD_TOKEN");
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
