// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GenesisCloud.Inputs
{

    public sealed class InstanceMetadataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("startupScript")]
        public Input<string>? StartupScript { get; set; }

        public InstanceMetadataGetArgs()
        {
        }
        public static new InstanceMetadataGetArgs Empty => new InstanceMetadataGetArgs();
    }
}
