// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package genesiscloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/genesiscloud/pulumi-genesiscloud/sdk/go/genesiscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Instance resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/genesiscloud/pulumi-genesiscloud/sdk/go/genesiscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := genesiscloud.NewInstance(ctx, "example", &genesiscloud.InstanceArgs{
//				Image:  pulumi.String("my-image-id"),
//				Region: pulumi.String("ARC-IS-HAF-1"),
//				SshKeyIds: pulumi.StringArray{
//					pulumi.String("my-ssh-key-id"),
//				},
//				Type: pulumi.String("vcpu-2_memory-4g"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import genesiscloud:index/instance:Instance example 18efeec8-94f0-4776-8ff2-5e9b49c74608
// ```
type Instance struct {
	pulumi.CustomResourceState

	// The timestamp when this image was created in RFC 3339.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The disk size of the instance in GB.
	DiskSize pulumi.IntOutput `pulumi:"diskSize"`
	// The dns name of the instance.
	DnsName pulumi.StringOutput `pulumi:"dnsName"`
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrOutput `pulumi:"floatingIpId"`
	Hostname     pulumi.StringOutput    `pulumi:"hostname"`
	Image        pulumi.StringOutput    `pulumi:"image"`
	// The resulting image ID of the instance.
	ImageId pulumi.StringOutput `pulumi:"imageId"`
	// Option to provide metadata. Currently supported is `startupScript`.
	Metadata InstanceMetadataPtrOutput `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name            pulumi.StringOutput    `pulumi:"name"`
	Password        pulumi.StringPtrOutput `pulumi:"password"`
	PlacementOption pulumi.StringOutput    `pulumi:"placementOption"`
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp pulumi.StringOutput `pulumi:"privateIp"`
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp pulumi.StringOutput `pulumi:"publicIp"`
	Region   pulumi.StringOutput `pulumi:"region"`
	// The id of the reservation the instance is associated with.
	ReservationId pulumi.StringPtrOutput `pulumi:"reservationId"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayOutput `pulumi:"securityGroupIds"`
	SshKeyIds        pulumi.StringArrayOutput `pulumi:"sshKeyIds"`
	// The instance status.
	Status   pulumi.StringOutput       `pulumi:"status"`
	Timeouts InstanceTimeoutsPtrOutput `pulumi:"timeouts"`
	Type     pulumi.StringOutput       `pulumi:"type"`
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayOutput `pulumi:"volumeIds"`
}

// NewInstance registers a new resource with the given unique name, arguments, and options.
func NewInstance(ctx *pulumi.Context,
	name string, args *InstanceArgs, opts ...pulumi.ResourceOption) (*Instance, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Image == nil {
		return nil, errors.New("invalid value for required argument 'Image'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Instance
	err := ctx.RegisterResource("genesiscloud:index/instance:Instance", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstance gets an existing Instance resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstance(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceState, opts ...pulumi.ResourceOption) (*Instance, error) {
	var resource Instance
	err := ctx.ReadResource("genesiscloud:index/instance:Instance", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Instance resources.
type instanceState struct {
	// The timestamp when this image was created in RFC 3339.
	CreatedAt *string `pulumi:"createdAt"`
	// The disk size of the instance in GB.
	DiskSize *int `pulumi:"diskSize"`
	// The dns name of the instance.
	DnsName *string `pulumi:"dnsName"`
	// The floating IP attached to the instance.
	FloatingIpId *string `pulumi:"floatingIpId"`
	Hostname     *string `pulumi:"hostname"`
	Image        *string `pulumi:"image"`
	// The resulting image ID of the instance.
	ImageId *string `pulumi:"imageId"`
	// Option to provide metadata. Currently supported is `startupScript`.
	Metadata *InstanceMetadata `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name            *string `pulumi:"name"`
	Password        *string `pulumi:"password"`
	PlacementOption *string `pulumi:"placementOption"`
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp *string `pulumi:"privateIp"`
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp *string `pulumi:"publicIp"`
	Region   *string `pulumi:"region"`
	// The id of the reservation the instance is associated with.
	ReservationId *string `pulumi:"reservationId"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	SshKeyIds        []string `pulumi:"sshKeyIds"`
	// The instance status.
	Status   *string           `pulumi:"status"`
	Timeouts *InstanceTimeouts `pulumi:"timeouts"`
	Type     *string           `pulumi:"type"`
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt *string `pulumi:"updatedAt"`
	// The volumes of the instance.
	VolumeIds []string `pulumi:"volumeIds"`
}

type InstanceState struct {
	// The timestamp when this image was created in RFC 3339.
	CreatedAt pulumi.StringPtrInput
	// The disk size of the instance in GB.
	DiskSize pulumi.IntPtrInput
	// The dns name of the instance.
	DnsName pulumi.StringPtrInput
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrInput
	Hostname     pulumi.StringPtrInput
	Image        pulumi.StringPtrInput
	// The resulting image ID of the instance.
	ImageId pulumi.StringPtrInput
	// Option to provide metadata. Currently supported is `startupScript`.
	Metadata InstanceMetadataPtrInput
	// The human-readable name for the instance.
	Name            pulumi.StringPtrInput
	Password        pulumi.StringPtrInput
	PlacementOption pulumi.StringPtrInput
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp pulumi.StringPtrInput
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp pulumi.StringPtrInput
	Region   pulumi.StringPtrInput
	// The id of the reservation the instance is associated with.
	ReservationId pulumi.StringPtrInput
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayInput
	SshKeyIds        pulumi.StringArrayInput
	// The instance status.
	Status   pulumi.StringPtrInput
	Timeouts InstanceTimeoutsPtrInput
	Type     pulumi.StringPtrInput
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt pulumi.StringPtrInput
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayInput
}

func (InstanceState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceState)(nil)).Elem()
}

type instanceArgs struct {
	// The disk size of the instance in GB.
	DiskSize *int `pulumi:"diskSize"`
	// The floating IP attached to the instance.
	FloatingIpId *string `pulumi:"floatingIpId"`
	Hostname     *string `pulumi:"hostname"`
	Image        string  `pulumi:"image"`
	// Option to provide metadata. Currently supported is `startupScript`.
	Metadata *InstanceMetadata `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name            *string `pulumi:"name"`
	Password        *string `pulumi:"password"`
	PlacementOption *string `pulumi:"placementOption"`
	Region          string  `pulumi:"region"`
	// The id of the reservation the instance is associated with.
	ReservationId *string `pulumi:"reservationId"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds []string          `pulumi:"securityGroupIds"`
	SshKeyIds        []string          `pulumi:"sshKeyIds"`
	Timeouts         *InstanceTimeouts `pulumi:"timeouts"`
	Type             string            `pulumi:"type"`
	// The volumes of the instance.
	VolumeIds []string `pulumi:"volumeIds"`
}

// The set of arguments for constructing a Instance resource.
type InstanceArgs struct {
	// The disk size of the instance in GB.
	DiskSize pulumi.IntPtrInput
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrInput
	Hostname     pulumi.StringPtrInput
	Image        pulumi.StringInput
	// Option to provide metadata. Currently supported is `startupScript`.
	Metadata InstanceMetadataPtrInput
	// The human-readable name for the instance.
	Name            pulumi.StringPtrInput
	Password        pulumi.StringPtrInput
	PlacementOption pulumi.StringPtrInput
	Region          pulumi.StringInput
	// The id of the reservation the instance is associated with.
	ReservationId pulumi.StringPtrInput
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayInput
	SshKeyIds        pulumi.StringArrayInput
	Timeouts         InstanceTimeoutsPtrInput
	Type             pulumi.StringInput
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayInput
}

func (InstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceArgs)(nil)).Elem()
}

type InstanceInput interface {
	pulumi.Input

	ToInstanceOutput() InstanceOutput
	ToInstanceOutputWithContext(ctx context.Context) InstanceOutput
}

func (*Instance) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (i *Instance) ToInstanceOutput() InstanceOutput {
	return i.ToInstanceOutputWithContext(context.Background())
}

func (i *Instance) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceOutput)
}

// InstanceArrayInput is an input type that accepts InstanceArray and InstanceArrayOutput values.
// You can construct a concrete instance of `InstanceArrayInput` via:
//
//	InstanceArray{ InstanceArgs{...} }
type InstanceArrayInput interface {
	pulumi.Input

	ToInstanceArrayOutput() InstanceArrayOutput
	ToInstanceArrayOutputWithContext(context.Context) InstanceArrayOutput
}

type InstanceArray []InstanceInput

func (InstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (i InstanceArray) ToInstanceArrayOutput() InstanceArrayOutput {
	return i.ToInstanceArrayOutputWithContext(context.Background())
}

func (i InstanceArray) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceArrayOutput)
}

// InstanceMapInput is an input type that accepts InstanceMap and InstanceMapOutput values.
// You can construct a concrete instance of `InstanceMapInput` via:
//
//	InstanceMap{ "key": InstanceArgs{...} }
type InstanceMapInput interface {
	pulumi.Input

	ToInstanceMapOutput() InstanceMapOutput
	ToInstanceMapOutputWithContext(context.Context) InstanceMapOutput
}

type InstanceMap map[string]InstanceInput

func (InstanceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (i InstanceMap) ToInstanceMapOutput() InstanceMapOutput {
	return i.ToInstanceMapOutputWithContext(context.Background())
}

func (i InstanceMap) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceMapOutput)
}

type InstanceOutput struct{ *pulumi.OutputState }

func (InstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (o InstanceOutput) ToInstanceOutput() InstanceOutput {
	return o
}

func (o InstanceOutput) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return o
}

// The timestamp when this image was created in RFC 3339.
func (o InstanceOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The disk size of the instance in GB.
func (o InstanceOutput) DiskSize() pulumi.IntOutput {
	return o.ApplyT(func(v *Instance) pulumi.IntOutput { return v.DiskSize }).(pulumi.IntOutput)
}

// The dns name of the instance.
func (o InstanceOutput) DnsName() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.DnsName }).(pulumi.StringOutput)
}

// The floating IP attached to the instance.
func (o InstanceOutput) FloatingIpId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.FloatingIpId }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

func (o InstanceOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

// The resulting image ID of the instance.
func (o InstanceOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

// Option to provide metadata. Currently supported is `startupScript`.
func (o InstanceOutput) Metadata() InstanceMetadataPtrOutput {
	return o.ApplyT(func(v *Instance) InstanceMetadataPtrOutput { return v.Metadata }).(InstanceMetadataPtrOutput)
}

// The human-readable name for the instance.
func (o InstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o InstanceOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) PlacementOption() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PlacementOption }).(pulumi.StringOutput)
}

// The private IPv4 IP-Address (IPv4 address).
func (o InstanceOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PrivateIp }).(pulumi.StringOutput)
}

// The public IPv4 IP-Address (IPv4 address).
func (o InstanceOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PublicIp }).(pulumi.StringOutput)
}

func (o InstanceOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The id of the reservation the instance is associated with.
func (o InstanceOutput) ReservationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.ReservationId }).(pulumi.StringPtrOutput)
}

// The security groups of the instance. If not provided will be set to the default security group.
func (o InstanceOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o InstanceOutput) SshKeyIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.SshKeyIds }).(pulumi.StringArrayOutput)
}

// The instance status.
func (o InstanceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o InstanceOutput) Timeouts() InstanceTimeoutsPtrOutput {
	return o.ApplyT(func(v *Instance) InstanceTimeoutsPtrOutput { return v.Timeouts }).(InstanceTimeoutsPtrOutput)
}

func (o InstanceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The timestamp when this image was last updated in RFC 3339.
func (o InstanceOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The volumes of the instance.
func (o InstanceOutput) VolumeIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.VolumeIds }).(pulumi.StringArrayOutput)
}

type InstanceArrayOutput struct{ *pulumi.OutputState }

func (InstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (o InstanceArrayOutput) ToInstanceArrayOutput() InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) Index(i pulumi.IntInput) InstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].([]*Instance)[vs[1].(int)]
	}).(InstanceOutput)
}

type InstanceMapOutput struct{ *pulumi.OutputState }

func (InstanceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (o InstanceMapOutput) ToInstanceMapOutput() InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) MapIndex(k pulumi.StringInput) InstanceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].(map[string]*Instance)[vs[1].(string)]
	}).(InstanceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceInput)(nil)).Elem(), &Instance{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceArrayInput)(nil)).Elem(), InstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceMapInput)(nil)).Elem(), InstanceMap{})
	pulumi.RegisterOutputType(InstanceOutput{})
	pulumi.RegisterOutputType(InstanceArrayOutput{})
	pulumi.RegisterOutputType(InstanceMapOutput{})
}
