// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package genesiscloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/genesiscloud/pulumi-genesiscloud/sdk/go/genesiscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Instance resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/genesiscloud/pulumi-genesiscloud/sdk/go/genesiscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := genesiscloud.NewInstance(ctx, "example", &genesiscloud.InstanceArgs{
//				Image:  pulumi.String("my-image-id"),
//				Region: pulumi.String("ARC-IS-HAF-1"),
//				SshKeyIds: pulumi.StringArray{
//					pulumi.String("my-ssh-key-id"),
//				},
//				Type: pulumi.String("vcpu-2_memory-4g_disk-80g"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
//
//	$ pulumi import genesiscloud:index/instance:Instance example 18efeec8-94f0-4776-8ff2-5e9b49c74608
//
// ```
type Instance struct {
	pulumi.CustomResourceState

	// The timestamp when this image was created in RFC 3339.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrOutput `pulumi:"floatingIpId"`
	// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
	// attribute is configured and changes, Terraform will destroy and recreate the resource.
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
	// recreate the resource.
	Image pulumi.StringOutput `pulumi:"image"`
	// The resulting image ID of the instance.
	ImageId pulumi.StringOutput `pulumi:"imageId"`
	// Option to provide metadata. Currently supported is `startup_script`.
	Metadata InstanceMetadataPtrOutput `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name pulumi.StringOutput `pulumi:"name"`
	// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
	// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
	// length must be at least 16.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// The placement option identifier in which instances are physically located relative to each other within a zone. For
	// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
	PlacementOption pulumi.StringOutput `pulumi:"placementOption"`
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp pulumi.StringOutput `pulumi:"privateIp"`
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp pulumi.StringOutput `pulumi:"publicIp"`
	// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
	// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
	Region pulumi.StringOutput `pulumi:"region"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayOutput `pulumi:"securityGroupIds"`
	// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
	// resource.
	SshKeyIds pulumi.StringArrayOutput `pulumi:"sshKeyIds"`
	// The instance status.
	Status   pulumi.StringOutput       `pulumi:"status"`
	Timeouts InstanceTimeoutsPtrOutput `pulumi:"timeouts"`
	// The instance type identifier. Learn more about instance types
	// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
	// Terraform will destroy and recreate the resource.
	Type pulumi.StringOutput `pulumi:"type"`
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayOutput `pulumi:"volumeIds"`
}

// NewInstance registers a new resource with the given unique name, arguments, and options.
func NewInstance(ctx *pulumi.Context,
	name string, args *InstanceArgs, opts ...pulumi.ResourceOption) (*Instance, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Image == nil {
		return nil, errors.New("invalid value for required argument 'Image'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Instance
	err := ctx.RegisterResource("genesiscloud:index/instance:Instance", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstance gets an existing Instance resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstance(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceState, opts ...pulumi.ResourceOption) (*Instance, error) {
	var resource Instance
	err := ctx.ReadResource("genesiscloud:index/instance:Instance", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Instance resources.
type instanceState struct {
	// The timestamp when this image was created in RFC 3339.
	CreatedAt *string `pulumi:"createdAt"`
	// The floating IP attached to the instance.
	FloatingIpId *string `pulumi:"floatingIpId"`
	// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
	// attribute is configured and changes, Terraform will destroy and recreate the resource.
	Hostname *string `pulumi:"hostname"`
	// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
	// recreate the resource.
	Image *string `pulumi:"image"`
	// The resulting image ID of the instance.
	ImageId *string `pulumi:"imageId"`
	// Option to provide metadata. Currently supported is `startup_script`.
	Metadata *InstanceMetadata `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name *string `pulumi:"name"`
	// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
	// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
	// length must be at least 16.
	Password *string `pulumi:"password"`
	// The placement option identifier in which instances are physically located relative to each other within a zone. For
	// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
	PlacementOption *string `pulumi:"placementOption"`
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp *string `pulumi:"privateIp"`
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp *string `pulumi:"publicIp"`
	// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
	// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
	Region *string `pulumi:"region"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
	// resource.
	SshKeyIds []string `pulumi:"sshKeyIds"`
	// The instance status.
	Status   *string           `pulumi:"status"`
	Timeouts *InstanceTimeouts `pulumi:"timeouts"`
	// The instance type identifier. Learn more about instance types
	// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
	// Terraform will destroy and recreate the resource.
	Type *string `pulumi:"type"`
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt *string `pulumi:"updatedAt"`
	// The volumes of the instance.
	VolumeIds []string `pulumi:"volumeIds"`
}

type InstanceState struct {
	// The timestamp when this image was created in RFC 3339.
	CreatedAt pulumi.StringPtrInput
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrInput
	// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
	// attribute is configured and changes, Terraform will destroy and recreate the resource.
	Hostname pulumi.StringPtrInput
	// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
	// recreate the resource.
	Image pulumi.StringPtrInput
	// The resulting image ID of the instance.
	ImageId pulumi.StringPtrInput
	// Option to provide metadata. Currently supported is `startup_script`.
	Metadata InstanceMetadataPtrInput
	// The human-readable name for the instance.
	Name pulumi.StringPtrInput
	// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
	// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
	// length must be at least 16.
	Password pulumi.StringPtrInput
	// The placement option identifier in which instances are physically located relative to each other within a zone. For
	// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
	PlacementOption pulumi.StringPtrInput
	// The private IPv4 IP-Address (IPv4 address).
	PrivateIp pulumi.StringPtrInput
	// The public IPv4 IP-Address (IPv4 address).
	PublicIp pulumi.StringPtrInput
	// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
	// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
	Region pulumi.StringPtrInput
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayInput
	// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
	// resource.
	SshKeyIds pulumi.StringArrayInput
	// The instance status.
	Status   pulumi.StringPtrInput
	Timeouts InstanceTimeoutsPtrInput
	// The instance type identifier. Learn more about instance types
	// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
	// Terraform will destroy and recreate the resource.
	Type pulumi.StringPtrInput
	// The timestamp when this image was last updated in RFC 3339.
	UpdatedAt pulumi.StringPtrInput
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayInput
}

func (InstanceState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceState)(nil)).Elem()
}

type instanceArgs struct {
	// The floating IP attached to the instance.
	FloatingIpId *string `pulumi:"floatingIpId"`
	// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
	// attribute is configured and changes, Terraform will destroy and recreate the resource.
	Hostname *string `pulumi:"hostname"`
	// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
	// recreate the resource.
	Image string `pulumi:"image"`
	// Option to provide metadata. Currently supported is `startup_script`.
	Metadata *InstanceMetadata `pulumi:"metadata"`
	// The human-readable name for the instance.
	Name *string `pulumi:"name"`
	// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
	// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
	// length must be at least 16.
	Password *string `pulumi:"password"`
	// The placement option identifier in which instances are physically located relative to each other within a zone. For
	// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
	PlacementOption *string `pulumi:"placementOption"`
	// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
	// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
	Region string `pulumi:"region"`
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
	// resource.
	SshKeyIds []string          `pulumi:"sshKeyIds"`
	Timeouts  *InstanceTimeouts `pulumi:"timeouts"`
	// The instance type identifier. Learn more about instance types
	// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
	// Terraform will destroy and recreate the resource.
	Type string `pulumi:"type"`
	// The volumes of the instance.
	VolumeIds []string `pulumi:"volumeIds"`
}

// The set of arguments for constructing a Instance resource.
type InstanceArgs struct {
	// The floating IP attached to the instance.
	FloatingIpId pulumi.StringPtrInput
	// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
	// attribute is configured and changes, Terraform will destroy and recreate the resource.
	Hostname pulumi.StringPtrInput
	// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
	// recreate the resource.
	Image pulumi.StringInput
	// Option to provide metadata. Currently supported is `startup_script`.
	Metadata InstanceMetadataPtrInput
	// The human-readable name for the instance.
	Name pulumi.StringPtrInput
	// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
	// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
	// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
	// length must be at least 16.
	Password pulumi.StringPtrInput
	// The placement option identifier in which instances are physically located relative to each other within a zone. For
	// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
	PlacementOption pulumi.StringPtrInput
	// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
	// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
	Region pulumi.StringInput
	// The security groups of the instance. If not provided will be set to the default security group.
	SecurityGroupIds pulumi.StringArrayInput
	// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
	// resource.
	SshKeyIds pulumi.StringArrayInput
	Timeouts  InstanceTimeoutsPtrInput
	// The instance type identifier. Learn more about instance types
	// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
	// Terraform will destroy and recreate the resource.
	Type pulumi.StringInput
	// The volumes of the instance.
	VolumeIds pulumi.StringArrayInput
}

func (InstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceArgs)(nil)).Elem()
}

type InstanceInput interface {
	pulumi.Input

	ToInstanceOutput() InstanceOutput
	ToInstanceOutputWithContext(ctx context.Context) InstanceOutput
}

func (*Instance) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (i *Instance) ToInstanceOutput() InstanceOutput {
	return i.ToInstanceOutputWithContext(context.Background())
}

func (i *Instance) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceOutput)
}

// InstanceArrayInput is an input type that accepts InstanceArray and InstanceArrayOutput values.
// You can construct a concrete instance of `InstanceArrayInput` via:
//
//	InstanceArray{ InstanceArgs{...} }
type InstanceArrayInput interface {
	pulumi.Input

	ToInstanceArrayOutput() InstanceArrayOutput
	ToInstanceArrayOutputWithContext(context.Context) InstanceArrayOutput
}

type InstanceArray []InstanceInput

func (InstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (i InstanceArray) ToInstanceArrayOutput() InstanceArrayOutput {
	return i.ToInstanceArrayOutputWithContext(context.Background())
}

func (i InstanceArray) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceArrayOutput)
}

// InstanceMapInput is an input type that accepts InstanceMap and InstanceMapOutput values.
// You can construct a concrete instance of `InstanceMapInput` via:
//
//	InstanceMap{ "key": InstanceArgs{...} }
type InstanceMapInput interface {
	pulumi.Input

	ToInstanceMapOutput() InstanceMapOutput
	ToInstanceMapOutputWithContext(context.Context) InstanceMapOutput
}

type InstanceMap map[string]InstanceInput

func (InstanceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (i InstanceMap) ToInstanceMapOutput() InstanceMapOutput {
	return i.ToInstanceMapOutputWithContext(context.Background())
}

func (i InstanceMap) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceMapOutput)
}

type InstanceOutput struct{ *pulumi.OutputState }

func (InstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (o InstanceOutput) ToInstanceOutput() InstanceOutput {
	return o
}

func (o InstanceOutput) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return o
}

// The timestamp when this image was created in RFC 3339.
func (o InstanceOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The floating IP attached to the instance.
func (o InstanceOutput) FloatingIpId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.FloatingIpId }).(pulumi.StringPtrOutput)
}

// The hostname of your instance. If not provided will be initially set to the `name` attribute. - If the value of this
// attribute is configured and changes, Terraform will destroy and recreate the resource.
func (o InstanceOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// The source image or snapshot of the instance. - If the value of this attribute changes, Terraform will destroy and
// recreate the resource.
func (o InstanceOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

// The resulting image ID of the instance.
func (o InstanceOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

// Option to provide metadata. Currently supported is `startup_script`.
func (o InstanceOutput) Metadata() InstanceMetadataPtrOutput {
	return o.ApplyT(func(v *Instance) InstanceMetadataPtrOutput { return v.Metadata }).(InstanceMetadataPtrOutput)
}

// The human-readable name for the instance.
func (o InstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The password to access the instance. Your password must have upper and lower chars, digits and length between 8-72.
// **Please Note**: Only one of `ssh_keys` or `password` can be provided. Password is less secure - we recommend you use an
// SSH key-pair. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The string
// length must be at least 16.
func (o InstanceOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// The placement option identifier in which instances are physically located relative to each other within a zone. For
// example A or B. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
func (o InstanceOutput) PlacementOption() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PlacementOption }).(pulumi.StringOutput)
}

// The private IPv4 IP-Address (IPv4 address).
func (o InstanceOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PrivateIp }).(pulumi.StringOutput)
}

// The public IPv4 IP-Address (IPv4 address).
func (o InstanceOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.PublicIp }).(pulumi.StringOutput)
}

// The region identifier. - If the value of this attribute changes, Terraform will destroy and recreate the resource. - The
// value must be one of: ["ARC-IS-HAF-1" "EUC-DE-MUC-1" "NORD-NO-KRS-1"].
func (o InstanceOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The security groups of the instance. If not provided will be set to the default security group.
func (o InstanceOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// The ssh keys of the instance. - If the value of this attribute changes, Terraform will destroy and recreate the
// resource.
func (o InstanceOutput) SshKeyIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.SshKeyIds }).(pulumi.StringArrayOutput)
}

// The instance status.
func (o InstanceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o InstanceOutput) Timeouts() InstanceTimeoutsPtrOutput {
	return o.ApplyT(func(v *Instance) InstanceTimeoutsPtrOutput { return v.Timeouts }).(InstanceTimeoutsPtrOutput)
}

// The instance type identifier. Learn more about instance types
// [here](https://developers.genesiscloud.com/instances#instance-types). - If the value of this attribute changes,
// Terraform will destroy and recreate the resource.
func (o InstanceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The timestamp when this image was last updated in RFC 3339.
func (o InstanceOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The volumes of the instance.
func (o InstanceOutput) VolumeIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.VolumeIds }).(pulumi.StringArrayOutput)
}

type InstanceArrayOutput struct{ *pulumi.OutputState }

func (InstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (o InstanceArrayOutput) ToInstanceArrayOutput() InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) Index(i pulumi.IntInput) InstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].([]*Instance)[vs[1].(int)]
	}).(InstanceOutput)
}

type InstanceMapOutput struct{ *pulumi.OutputState }

func (InstanceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (o InstanceMapOutput) ToInstanceMapOutput() InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) MapIndex(k pulumi.StringInput) InstanceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].(map[string]*Instance)[vs[1].(string)]
	}).(InstanceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceInput)(nil)).Elem(), &Instance{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceArrayInput)(nil)).Elem(), InstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceMapInput)(nil)).Elem(), InstanceMap{})
	pulumi.RegisterOutputType(InstanceOutput{})
	pulumi.RegisterOutputType(InstanceArrayOutput{})
	pulumi.RegisterOutputType(InstanceMapOutput{})
}
