// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * SSH key resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as genesiscloud from "@genesiscloud/pulumi-genesiscloud";
 *
 * const example = new genesiscloud.SSHKey("example", {publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBOpdKM8wSI07+PO4xLDL7zW/kNWGbdFXeHyBU1TRlBn alice@example.com"});
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import genesiscloud:index/sSHKey:SSHKey example 18efeec8-94f0-4776-8ff2-5e9b49c74608
 * ```
 */
export class SSHKey extends pulumi.CustomResource {
    /**
     * Get an existing SSHKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SSHKeyState, opts?: pulumi.CustomResourceOptions): SSHKey {
        return new SSHKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'genesiscloud:index/sSHKey:SSHKey';

    /**
     * Returns true if the given object is an instance of SSHKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SSHKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SSHKey.__pulumiType;
    }

    /**
     * The timestamp when this SSH key was created in RFC 3339.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * The fingerprint of the SSH key.
     */
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    /**
     * The human-readable name for the SSH key.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
     */
    public readonly publicKey!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.SSHKeyTimeouts | undefined>;

    /**
     * Create a SSHKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SSHKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SSHKeyArgs | SSHKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SSHKeyState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["fingerprint"] = state ? state.fingerprint : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["publicKey"] = state ? state.publicKey : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as SSHKeyArgs | undefined;
            if ((!args || args.publicKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["publicKey"] = args ? args.publicKey : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SSHKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SSHKey resources.
 */
export interface SSHKeyState {
    /**
     * The timestamp when this SSH key was created in RFC 3339.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The fingerprint of the SSH key.
     */
    fingerprint?: pulumi.Input<string>;
    /**
     * The human-readable name for the SSH key.
     */
    name?: pulumi.Input<string>;
    /**
     * SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
     */
    publicKey?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.SSHKeyTimeouts>;
}

/**
 * The set of arguments for constructing a SSHKey resource.
 */
export interface SSHKeyArgs {
    /**
     * The human-readable name for the SSH key.
     */
    name?: pulumi.Input<string>;
    /**
     * SSH public key. - If the value of this attribute changes, Terraform will destroy and recreate the resource.
     */
    publicKey: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.SSHKeyTimeouts>;
}
